### ISSUE TITLE
atom 1.19.0 No package size is displayed

### ISSUE THREAD

**Issue by id77** [siddharthkp/atom-import-cost#5]
No package size is displayed
No error
No warning
No size

**Comment by siddharthkp** [comment]
Wut, sorry, i didn't get you

**Comment by Julian-B90** [comment]
![bildschirmfoto 2017-08-14 um 11 09 57](https://user-images.githubusercontent.com/4377396/29265393-26cdafa2-80e1-11e7-9267-8be10f328221.png)

ATOM Version: 1.19.0 x64

**Comment by trufflesprouts** [comment]
Same :(

**Comment by siddharthkp** [comment]
Yep, it broke with the latest release. I'll check this out soon, does anyone want to take a shot at it?

**Comment by trufflesprouts** [comment]
![screen shot 2017-08-15 at 12 02 41 am](https://user-images.githubusercontent.com/22350261/29291746-3472c270-814d-11e7-9f75-01161f9122fb.png)
Looks like a problem with the API.

**Comment by siddharthkp** [comment]
Ah damn, alright. A resurection of https://github.com/siddharthkp/atom-import-cost/pull/3 should fix it.

**Comment by reznord** [comment]
@siddharthkp it is still the same issue for me even with `v0.9.0` too

**Comment by mattiascaricato** [comment]
Same error with Atom 1.19.1

![image](https://user-images.githubusercontent.com/4216599/30244164-09eaf314-958f-11e7-94f7-439f0eff40ed.png)

**Comment by vertic4l** [comment]
Will this be fixed somewhen? Would like to use it...
**Edit:** Ok, it works partially. Stops working within deep nested module trees.

**Comment by damianobarbati** [comment]
@vertic4l does this work for you? I don't see anything when importing ES modules (no size displayed).
